---
kind: pipeline
type: docker
name: ci

steps:
  - name: test
    image: node:21-alpine
    commands:
      - yarn install
      - yarn test

---
kind: pipeline
type: exec
name: on-host
depends_on:
  - ci
steps:
  - name: build
    when:
      branch:
        - main
    environment:
      CI_DEPLOY_PWD:
        from_secret: CI_DEPLOY_PWD
    commands:
      - cd $CI_DEPLOY_PWD
      - ./deploy.sh
---
kind: signature
hmac: 4f5b887283b42a5c4a4f9fff11768567fad687aed566458721021a03c1cdf153

...
