kind: pipeline
type: docker
name: ci

steps:
  - name: test
    image: node:21-alpine
    commands:
      - yarn install
      - yarn test

---
kind: pipeline
type: exec
name: on-host
depends_on:
  - ci
steps:
  - name: build
    environment:
      PWD:
        from_secret: KUKEI_WEB_PWD
    commands:
      - cd $PWD && git pull
      - cd $PWD && docker compose build
      - cd $PWD && docker compose down && docker compose up -d
